build_from:
  aarch64: "homeassistant/aarch64-base-debian:buster"
  amd64: "homeassistant/amd64-base-debian:buster"
#      "armv7": "ghcr.io/zeehio/addons-base/base/armv7:edge",
#        "i386": "ghcr.io/zeehio/addons-base/base/i386:edge"
