name: Kodi
version: 0.0.31
stage: experimental
slug: kodi
image: zeehio/ha-kodi-{arch}
description: Kodi server
url: https://github.com/zeehio/hassio-addons
init: false
ingress: false
startup: system
arch:
  - aarch64
boot: auto
audio: true
devices:
  - /dev/dma_heap
video: true
usb: true
stdin: true
full_access: false
map:
  - media
host_network: true
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Kodi HTTP API
options:
  webserver: true
  webserverauthentication: true
  webserverusername: "hassio"
  webserverpassword: ""
schema:
  webserver: bool
  webserverauthentication: bool
  webserverusername: str
  webserverpassword: password

