name: Radicale
version: 0.0.27
stage: experimental
slug: radicale
image: zeehio/ha-radicale-{arch}
panel_icon: mdi:calendar
init: false
description: Radicale is a small but powerful CalDAV (calendars, todo-lists) and CardDAV (contacts) server
url: https://github.com/zeehio/hassio-addons
auth_api: true
webui: http://[HOST]:[PORT:5233]/
ingress: false
ingress_port: 5233
ingress_entry: /
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
audio: false
ports:
  5233/tcp: 5233
ports_description:
  5233/tcp: Radicale
map:
  - share:rw
options: {}
schema: {}
