on:
  push:
    branches:
      - master
    paths:
      - 'kodi/**'

name: Build kodi

jobs:
  build-kodi:
    name: "Kodi"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull the Docker Image builder
      run: docker pull homeassistant/amd64-builder
    - name: Build for all archs
      run: |
            docker run --rm --privileged \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v ~/.docker:/root/.docker \
              -v $PWD/kodi:/data \
              homeassistant/amd64-builder \
              --all \
              -t /data 
